Repository cyrraz/plothist, pull requests merged in 2023-06, with the labels that each got.

#2 Hist2d
  examples/jupyter/basic_examples.ipynb
  examples/jupyter/hep_examples.ipynb
  examples/python/basic_examples.py
  examples/python/hep_examples.py
  plothist/plotters.py
Labels: enhancement

#3 Documentation implemented
  .gitignore
  README.md
  README.rst
  docs/advanced/hep_examples.rst
  docs/basics/1d_hist.rst
  docs/basics/2d_hist.rst
  docs/conf.py
  docs/documentation/documentation.rst
  docs/img/1d_hist_simple.svg
  docs/img/2d_hist_simple.svg
  docs/img/2d_hist_uneven.svg
  docs/img/hep_examples_dataMC_flatten2D.svg
  docs/img/hep_examples_dataMC_stacked.svg
  docs/img/hep_examples_dataMC_unstacked.svg
  docs/img/intro_2dhist_complexe.svg
  docs/img/intro_2dhist_hep.svg
  docs/img/intro_hist_hep.svg
  docs/index.rst
  docs/usage/installation.rst
  examples/advanced_examples.py
  examples/basic_examples.py
  examples/hep_examples.py
  examples/jupyter/advanced_examples.ipynb
  examples/jupyter/basic_examples.ipynb
  examples/jupyter/hep_examples.ipynb
  examples/jupyter/style_example.ipynb
  examples/python/basic_examples.py
  examples/style_example.py
  plothist/__init__.py
  plothist/generate_dummy_data.py
  plothist/hep_plotters.py
  plothist/plotters.py
Labels: documentation

#6 preparing for PyPI publication
  docs/advanced/hep_examples.rst
  docs/basics/1d_hist.rst
  docs/basics/2d_hist.rst
  plothist/__init__.py
  pyproject.toml
Labels: update

#10 paper and presentation style ready
  README.rst
  docs/advanced/advanced_examples.rst
  docs/advanced/hep_examples.rst
  docs/basics/1d_hist.rst
  docs/basics/2d_hist.rst
  docs/documentation/documentation.rst
  docs/img/hep_examples_dataMC_flatten2D.svg
  docs/img/hep_examples_dataMC_stacked.svg
  docs/img/hep_examples_dataMC_stacked_publication.svg
  docs/img/hep_examples_dataMC_unstacked.svg
  docs/img/intro_2dhist_complexe.svg
  docs/img/intro_2dhist_hep.svg
  docs/img/intro_hist_hep.svg
  docs/index.rst
  examples/hep_examples.py
  plothist/__init__.py
  plothist/hep_plotters.py
  plothist/plothist_style.py
  plothist/plotters.py
  plothist/presentation_style.mplstyle
  plothist/publication_style.mplstyle
  plothist/style.mplstyle
Labels: documentation, enhancement

#12 doc version
  docs/conf.py
Labels: documentation
